# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
unsetopt autocd
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/twined/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# coloured prompt
autoload -U colors && colors

# superglobs
setopt extendedglob
unsetopt caseglob

# load reporting
REPORTTIME=60

function collapse_pwd {
    echo $(pwd | sed -e "s,^$HOME,~,")
}

PROMPT="%{$fg[cyan]%}%n@%m %{$reset_color%}%{$fg_bold[green]%}%~%#%{$reset_color%} "
